name: Task 1 - Multiple Workflow Triggers

on:
  push:
    branches:
      - dev

  workflow_dispatch:
    inputs:
      environment:
        description: Select the environment
        required: true
        type: choice
        options:
          - dev
          - qa
          - prod

jobs:
  test-workflow:
    runs-on: windows-latest

    steps:
      - name: Print message
        run: echo Workflow is running successfully

      - name: Print selected environment
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: echo Selected Environment: ${{ github.event.inputs.environment }}
