name: Task 1 - Multiple(Feature_branch2)

on:
  push:
    branches:
      - feature_branch

  workflow_dispatch:
    inputs:
      environment:
        description: Select the environment
        required: true
        type: choice
        options:
          - dev
          - qa
          - prod

jobs:
  test-workflow:
    runs-on: windows-latest

    steps:
      - name: Print message
        run: echo Workflow is running successfully

      - name: Print selected environment
        if: github.event_name == 'workflow_dispatch'
        run: echo Selected environment is ${{ inputs.environment }}
