name: Task 2 - Pull Request Target Workflow (task 2)

on:
  pull_request_target:
    branches:
      - main
    types:
      - opened
      - closed

jobs:
  pr-target:
    runs-on: windows-latest

    steps:
      - name: Print message (main branch)
        run: echo pull_request_target workflow is running

      - name: Print branch name
        run: echo PR is created for ${{ github.base_ref }}

      - name: Print PR action type
        run: echo PR action is ${{ github.event.action }}

    
