name: Task 2 - Pull Request Workflow

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - closed

jobs:
  pr-workflow:
    runs-on: windows-latest

    steps:
      - name: Print message
        run: echo Pull Request workflow is running

      - name: Print PR action type
        run: echo Pull Request action is ${{ github.event.action }}
