name: Task 2 - Pull Request Workflow

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - closed

jobs:
  pr-workflow:
    runs-on: windows-latest

    steps:
      - name: Print message
        run: echo Pull Request workflow is running

      - name: Print branch name
        run: echo PR is created for ${{ github.base_ref }}
