name: Task 3 - Conditional Job Execution (Run on push, but job should run only if branch = main)

on:
  push:

jobs:
  run-only-on-main:
    if: github.ref == 'refs/heads/main'
    runs-on: windows-latest

    steps:
      - name: Print message
        run: echo Run on push, but job should run only if branch = main
